# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16694769a82d68b21138a741cc311ee2e6465584decf62d6d9d9f87bb4b48e08253f4d99dd2b2aca9906e67ba63e2dac6a35ac46e02b645a466760e9939d969c

test:
  secret_key_base: 3bb978cfb6cb9f273cee3e6415e96d50cf3b5f418b875ca50f5562b924ee92d077edde0c0b1d4cc80a3e9548078eaf950053b18dfe12245608350fec91c383e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
